# Generated by Django 4.2.4 on 2023-10-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_to_do_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_data',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='to_do',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.to_do_data'),
            preserve_default=False,
        ),
    ]
