# Generated by Django 4.2.4 on 2023-10-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_to_do_data_user_myuser_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='to_do',
        ),
        migrations.AddField(
            model_name='to_do_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.myuser'),
        ),
    ]
