# Generated by Django 4.2.4 on 2023-10-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0005_remove_myuser_to_do_to_do_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
