# Generated by Django 4.2.4 on 2023-10-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 10, 6, 18, 46, 31, 598215))),
            ],
        ),
    ]
